#!/usr/bin/env python3
"""Build jafner.com static site by injecting partials into source pages."""

import os
import re
import shutil
import stat
from pathlib import Path


def _force_remove(func, path, _exc):
    """rmtree onerror handler: clear the read-only bit and retry.

    OneDrive "Files On-Demand" leaves dehydrated files/dirs as read-only
    reparse points, which os.rmdir/os.unlink refuse to delete. Clearing
    the read-only attribute lets the delete go through.
    """
    os.chmod(path, stat.S_IWRITE)
    func(path)

ROOT    = Path(__file__).parent
SRC     = ROOT / 'src'
COMMON  = ROOT / 'common'
PUBLIC  = ROOT / 'public'

# Partials
nav    = (COMMON / 'nav.html').read_text(encoding='utf-8')
footer = (COMMON / 'footer.html').read_text(encoding='utf-8')
ai_tag_template = (COMMON / 'ai-tag.html').read_text(encoding='utf-8')

# ---------------------------------------------------------------------
# AI content disclosure tag — single source of truth.
# Change the wording here and every page updates on the next build.
# A page opts in by placing a marker in its src file, e.g. <!--AI-TAG:1-->
# where the number is the level (1-4). Pages with no marker get no tag.
# ---------------------------------------------------------------------
AI_LEVELS = {
    '1': {
        'chip':    'AI · none',
        'title':   'Human-made',
        'desc':    'Everything here was written and built by a human. No AI involved.',
        'content': 'human',
        'build':   'human',
    },
    '2': {
        'chip':    'AI · build',
        'title':   'Human content, AI-assisted build',
        'desc':    'The words are human-written. AI only helped with the HTML, layout and formatting.',
        'content': 'human',
        'build':   'AI-assisted',
    },
    '3': {
        'chip':    'AI · assisted',
        'title':   'AI-supported',
        'desc':    'The content and the build were created with AI assistance, then reviewed and edited by a human.',
        'content': 'AI-assisted',
        'build':   'AI-assisted',
    },
    '4': {
        'chip':    'AI · generated',
        'title':   'AI content, human-directed',
        'desc':    'The content and build were generated by AI under human direction and review.',
        'content': 'AI-generated',
        'build':   'AI-generated',
    },
}

AI_TAG_MARKER = re.compile(r'<!--AI-TAG:(\d+)-->')


def render_ai_tags(html, page_name):
    """Replace every <!--AI-TAG:N--> marker with the built tag for level N."""
    def _sub(match):
        level = match.group(1)
        data = AI_LEVELS.get(level)
        if data is None:
            print(f'  WARNING: {page_name} uses unknown AI level {level!r}; skipping tag')
            return ''
        tag = ai_tag_template.replace('{{LEVEL}}', level)
        for key, value in data.items():
            tag = tag.replace('{{' + key.upper() + '}}', value)
        return tag
    return AI_TAG_MARKER.sub(_sub, html)

# Clean and recreate public/
if PUBLIC.exists():
    shutil.rmtree(PUBLIC, onerror=_force_remove)
PUBLIC.mkdir()

# Static assets that should be copied as-is (not processed)
for asset_dir in ['assets', 'css', 'js', 'images']:
    src_assets = ROOT / asset_dir
    if src_assets.exists():
        shutil.copytree(src_assets, PUBLIC / asset_dir)

# Also copy style.css from root if it lives there
for top_file in ['style.css', 'favicon.ico', 'robots.txt']:
    f = ROOT / top_file
    if f.exists():
        shutil.copy(f, PUBLIC / top_file)

# Build each HTML page
pages_built = 0
for page in SRC.glob('*.html'):
    page_name = page.name

    # Mark the active nav link based on this page's filename
    nav_with_active = re.sub(
        rf'href="/{page_name}"',
        rf'href="/{page_name}" aria-current="page"',
        nav,
    )

    html = (page.read_text(encoding='utf-8')
        .replace('<!--NAV-->', nav_with_active)
        .replace('<!--FOOTER-->', footer))
    html = render_ai_tags(html, page_name)

    (PUBLIC / page_name).write_text(html, encoding='utf-8')
    pages_built += 1
    print(f'  built {page_name}')

print(f'\nDone: {pages_built} pages built into {PUBLIC}/')